In [9]:
#question 1

#sort the list and find min and max age
ages=[19,22,19,24,20,25,26,24,25,24]
ages.sort()                                 #sorting the list
print('The sorted list:',ages)
print('The max age is:',max(ages))          #finding the largest and smallest element by using max() and min()
print('The min age is:',min(ages)) 

#adding min and max of ages to the list again
ages.append(min(ages))                     #using append()to add the maximum and minimum elements into the list elements into the list
ages.append(max(ages))
print(ages)
ages.sort()                                #sorting the ages again for calculating the median
print(ages)

#finding the median
m=0
l=len(ages)
if l%2==0:
    m=int(((l/2)+(l/2+1))/2)
else :
    m=int(age(l+1)/2)
print('The median age of the list is: ',ages[m])

#finding the average
avg=sum(ages)/len(ages)
print('The average age of the list is:',avg)

#finding the range
range_age=max(ages)-min(ages)
print('The range of the ages:',range_age)


The sorted list: [19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
The max age is: 26
The min age is: 19
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 19, 26]
[19, 19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 26]
The median age of the list is:  24
The average age of the list is: 22.75
The range of the ages: 7


In [23]:
#question 2
#creating an empty dictionary called dog
dog={}                                             #creating a empty dictionary named dog and printing it
print(dog)
dog={'name' : 'rico','breed' : 'golden retriever','legs' : 'four','age' : '1 year'}  #adding the keys and values to the dictionary dog
print('\ndog:',dog)

#creating a student dictionary
stu_dict={}
stu_dict={'first_name':'swetha',
          'last name':'nambari',
          'gender':'female',
          'age':'21',
          'marital_status':'single',
          'skills':['C','python','java'],
          'country':'USA',
          'city':'Overland park',
          'address':{'street:123 opop',
                    'zip:1234'}}
print('\nSTUDENT DICTIONARY:\n',stu_dict)
#length of the student dictionary
print('\nThe length of the student dictionary is:',len(stu_dict))
#value of the skills and the datatype of list
print('\nthe value of the skills:',stu_dict.get('skills'))                #.get(skills) is used to get the value of the skills
print('\nthe datatype of the key skills:',type(stu_dict['skills']))
#modifying the skills
stu_dict['skills'].append('javascript')                                   #adding skills to the existing skills
print('\n',stu_dict.get('skills'))
#keys as a list
keys=stu_dict.keys()
print('\n the dictionary keys as a list:\n',keys)
#values as a list
values=stu_dict.values()
print('\n the dictionary values as a list:\n',values)

{}

dog: {'name': 'rico', 'breed': 'golden retriever', 'legs': 'four', 'age': '1 year'}

STUDENT DICTIONARY:
 {'first_name': 'swetha', 'last name': 'nambari', 'gender': 'female', 'age': '21', 'marital_status': 'single', 'skills': ['C', 'python', 'java'], 'country': 'USA', 'city': 'Overland park', 'address': {'street:123 opop', 'zip:1234'}}

The length of the student dictionary is: 9

the value of the skills: ['C', 'python', 'java']

the datatype of the key skills: <class 'list'>

 ['C', 'python', 'java', 'javascript']

 the dictionary keys as a list:
 dict_keys(['first_name', 'last name', 'gender', 'age', 'marital_status', 'skills', 'country', 'city', 'address'])

 the dictionary values as a list:
 dict_values(['swetha', 'nambari', 'female', '21', 'single', ['C', 'python', 'java', 'javascript'], 'USA', 'Overland park', {'street:123 opop', 'zip:1234'}])


In [58]:
#question 3
#creating tuples containing names of brothers and sisters
sisters=('lik','lat','honey')
brothers=('kar','ban','maji')
print(sisters)
print(brothers)
siblings=sisters+brothers      #joining the siters and brothers tuple by concating both the brothers and sisters tuples
print('siblings:',siblings)              
print('The number of siblings:',len(siblings))     #finding the number of siblings using len()..the answer would be 6
family_members=list(siblings)
family_members.append('sri')          #adding mother and father to the siblings list and assigning it to the family members
family_members.append('vee')
print('family members:',family_members)

('lik', 'lat', 'honey')
('kar', 'ban', 'maji')
siblings: ('lik', 'lat', 'honey', 'kar', 'ban', 'maji')
The number of siblings: 6
family members: ['lik', 'lat', 'honey', 'kar', 'ban', 'maji', 'sri', 'vee']


In [33]:
#question 4
it_companies={'Facebook','Google','Microsoft','Apple','IBM','Oracle','Amazon'}
print(it_companies)
p=len(it_companies)                           #length of the companies
print('The length of the set is:',p)
it_companies.add('Twitter')                   #adding Twitter to the it_companies using add()
print(it_companies)
it_companies.update(['TCS','Infosys','HP'])   #inserting multiple it companies at once using update()
print(it_companies)
it_companies.remove('HP')                     #removing one of the itcompanies from the set 
print(it_companies)

{'IBM', 'Microsoft', 'Google', 'Apple', 'Facebook', 'Oracle', 'Amazon'}
The length of the set is: 7
{'IBM', 'Twitter', 'Microsoft', 'Google', 'Apple', 'Facebook', 'Oracle', 'Amazon'}
{'IBM', 'Google', 'Oracle', 'TCS', 'Infosys', 'HP', 'Microsoft', 'Twitter', 'Facebook', 'Apple', 'Amazon'}
{'IBM', 'Google', 'Oracle', 'TCS', 'Infosys', 'Microsoft', 'Twitter', 'Facebook', 'Apple', 'Amazon'}


In [31]:
it_companies.discard('Cape Gemini')    #does not give any error when we use it to take out an element which is not present in the set
it_companies.remove('Cape gemini')     #error arises..when we use remove an element which is present in the set

KeyError: 'Cape gemini'

In [44]:
A={19,22,24,20,25,26}
B={19,22,20,25,26,24,28,27}
C=A.union(B)                       #joining the sets A and B
print(C)
print(A.intersection(B))           #finding the intersection of the both sets
print(A.issubset(B))               #finding if A is a subset of set B...expected outcome should be true as all the elements in setA exist in setB
print(B.isdisjoint(A))             #finding if set A and set B are disjoint(ie;there should not be any common elements betweeen the both.) 
                                   #the outcome for this should be false


{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26}
True
False


In [49]:
print(A.symmetric_difference(B))    #finding the symetric difference between the two sets
A.update(B)                         #joining A with B
print(A)                          
B.update(A)                         #joining B with A
print(B)

set()
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26, 27, 28}


In [36]:
#deleting all the sets
del it_companies         #deleting the set it_companines...if we try to print out..we would get an error as it has been already removed
del A
del B
print(it_companies)

NameError: name 'it_companies' is not defined

In [40]:
#converting age to set and comparing the length
age=[22,19,24,25,26,24,25,24]
sage=set(age)                   #converting age(list) into a set
print(sage)
print(len(age)>len(sage))       #comparing the length of age and sage

{19, 22, 24, 25, 26}
True


In [51]:
#question5
#calculating the area and the circumfrence of a circle
rad=30
pi=3.14
_area_of_circle_=pi*rad*rad
print(_area_of_circle_)
_circum_of_the_circle=2*pi*rad
print(_circum_of_the_circle)
#the remaing part of the question is continued down


2826.0
188.4


In [2]:
#calculating the area by taking radius as the user input
pi=3.14
rad=int(input("enter the radius of the circle:"))  #taking radius as the user input
area=pi*rad*rad
print('area of the circle is:%d'%area)

enter the radius of the circle:20
area of the circle is:1256


In [54]:
#question6
#finding the number of unique words and getting them by using split and set method
str='I am a teacher and I love to inspire and teach people'
u=set(str.split(" "))          #splitting the string and placing them in a set..
print(len(u))
print(u)        
        

10
{'and', 'inspire', 'to', 'teacher', 'teach', 'I', 'am', 'love', 'people', 'a'}


In [55]:
#question 7
#tab escape sequence to get the following
print('Name\t\tAge\tCountry\tCity\n')           #using\t and \n to get the desired format
print('Asabeneh\t250\tFinland\tHelinski')

Name		Age	Country	City

Asabeneh	250	Finland	Helinski


In [56]:
#question 8
#string formatting metod
res='radius ={}\narea=3.14*radius**{}\nThe area of the circle with {} is {} meters square '.format(10,2,10,int(area))
print(res)

radius =10
area=3.14*radius**2
The area of the circle with 10 is 314 meters square 


In [3]:
#question 9
#reading the weight(in pounds) of n students into a list and converting them into kilogrms
n=int(input('enter the number of students:'))      #user input of the n number of students
weights_lb=[]                                      #creating empty lists
weights_kg=[]
for i in range(n):                                 #using for loop for taking the values into the list and converting with range as the number of students
    lb=int(input("enter the weights in lb:"))      #user input of weight in pounds
    weights_lb.append(lb)                          #appendingthe given user inp into a list
    kg=lb*0.453592                                 #converting the user inputlb into kg
    weights_kg.append(kg)                          #appending the converted weights into the new list(weight_kg)
print('\nthe weights in lb:',weights_lb)
print('\nthe weights in kilograms:',weights_kg)
    

enter the number of students:5
enter the weights in lb:162
enter the weights in lb:173
enter the weights in lb:189
enter the weights in lb:192
enter the weights in lb:200

the weights in lb: [162, 173, 189, 192, 200]

the weights in kilograms: [73.481904, 78.471416, 85.728888, 87.089664, 90.7184]


In [14]:
#question 10
import numpy as ng
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

CA=ng.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]])
CB=ng.array([0,0,1,1,1,0,0,0])
print('the points in the dataset are:',CA)
print('CB-class label of the dataset CA:',CB)
CA_train,CA_test,CB_train,CB_test=train_test_split(CA,CB,test_size=0.50,random_state=0,shuffle=False)
print(CA_train)
print(CB_train)
standscalar=StandardScaler()
CA_train=standscalar.fit_transform(CA_train)
CA_test=standscalar.transform(CA_test)

classify=KNeighborsClassifier(n_neighbors=3)
classify.fit(CA_train,CB_train)
CB_predict=classify.predict(CA_test)
print('CB test data prediction class labels',CB_predict)

confusionmatrix=confusion_matrix(CB_test,CB_predict)
print('the confusion matrix is:\n',confusionmatrix)

tpn=sum(sum(confusionmatrix))
accuracy=(confusionmatrix[0,0]+confusionmatrix[1,1])/tpn
print('the accuracy is:',accuracy)
sen=confusionmatrix[1,1]/(confusionmatrix[1,0]+confusionmatrix[1,1])
print('the sensitivity is:',sen)
spe=confusionmatrix[0,0]/(confusionmatrix[0,0]+confusionmatrix[0,1])
print('the specificity is:',spe)






the points in the dataset are: [[ 1  0]
 [ 2  0]
 [ 3  0]
 [ 6  0]
 [ 6  0]
 [ 7  0]
 [10  0]
 [11  0]]
CB-class label of the dataset CA: [0 0 1 1 1 0 0 0]
[[1 0]
 [2 0]
 [3 0]
 [6 0]]
[0 0 1 1]
CB test data prediction class labels [1 1 1 1]
the confusion matrix is:
 [[0 3]
 [0 1]]
the accuracy is: 0.25
the sensitivity is: 1.0
the specificity is: 0.0
